### ISSUE TITLE
Merge parse and identical transforms at forks + allow sorting x/y-scale for layered plots

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite#2177]
Started in https://github.com/vega/vega-lite/tree/dom/parse-merge but it's still not correct.

**Comment by kanitw** [comment]
- [ ] overlay_line_short.vl.json is one example that needs this

**Comment by kanitw** [comment]
- [ ] the example in https://github.com/vega/vega-lite/issues/2964 also needs this

**Comment by domoritz** [comment]
In #2964 the two nodes are actually equivalent. We should definitely handle that case as it is trivial.

**Comment by g3o2** [comment]
Given that there a few issues dealing with sorting in layered plots, some of them closed, I am bit confused regarding the status: is sorting x/y scale for layered plots work in progress ?

**Comment by domoritz** [comment]
@g3o2 I think it's working. Do you have an example where it doesn't work?

**Comment by g3o2** [comment]
@domoritz  maybe I'm doing something wrong ...

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28},
      {"a": "B","b": 55},
      {"a": "C","b": 43}
    ]
  },
  "layer": [{
    "mark": "bar",
    "encoding": {
      "y": {
        "field": "a", "type": "ordinal", 
        "sort": {"field": "b", "op": "mean", "order": "descending" }
      },
      "x": {"field": "b", "type": "quantitative"}
    }
  }, {
    "mark": {
      "type": "text",
      "align": "left",
      "baseline": "middle",
      "dx": 3
    },
    "encoding": {
      "y": {
        "field": "a", "type": "ordinal", 
        "sort": {"field": "b", "op": "mean", "order": "descending" }
      },
      "x": {"field": "b", "type": "quantitative"},
      "text": {"field": "b", "type": "quantitative"}
    }
  }]
}
```

![image](https://user-images.githubusercontent.com/12123506/36909289-e54f4b1c-1e3d-11e8-806c-420435cf00a0.png)

**Comment by domoritz** [comment]
@g3o2 As noted in https://github.com/vega/vega-lite/issues/2964#issuecomment-327625787, it is not possible to union a scale domain with an aggregation other than count. However, in your case the data is coming from the same domain so the easy fix is to just use the one. However, layer creates a forked dataflow and we are currently not merging common subtrees (that's what this issue is about) and so Vega-Lite has no way of knowing that the two domains are actually the same (one may be filtered or otherwise transformed). You can sort with count aggregation or some other sort order but the spec above doesn't work yet. The fix will come!

**Comment by g3o2** [comment]
@domoritz thank you for clarifying!

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/issues/3797 also needs this.

**Comment by kanitw** [comment]
This is mostly addressed in #3959 except for merging identical transforms at forks

**Comment by quantoid** [comment]
@kanitw we're still seeing this issue when layering charts (in Altair) with `sort="-x"` on the y-axis.
