### ISSUE TITLE
data with sub-objects fails in vegalite

### ISSUE THREAD

**Issue by nyurik** [vega/vega-lite#3137]
Plotting [this data](https://gist.github.com/nyurik/438d0c99c408f34c192dd4ca3868c177) as a scatter plot fails.  The Vega seems to be generated partially with dots, and partially as escaped.
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 300,
  "height": 300,
  "data": {
    "url": "https://gist.githubusercontent.com/nyurik/438d0c99c408f34c192dd4ca3868c177/raw/1d69e6c9690283e1aed28a37bfda19ea7978f7c5/reco1.json",
    "format": {"property": "hits.hits"}
  },
  "mark": "point",
  "encoding": {
    "x": {
      "field": "_source.reco",
      "type": "quantitative"
    },
    "y": {
      "field": "_source.yes",
      "type": "quantitative"
    }
  }
}
```

**Comment by domoritz** [comment]
Vega-Lite does not support nested properties because people might have fields with `.` in them and we would like to support that. If you can make a strong case for different behavior, we can change it.

**Comment by nyurik** [comment]
@domoritz, at this point dots do not work in either case (see graph below - it uses a data set with dots).  In order for it work, I had to search for all "source.*" and replace them with "source\\.*" in the generated vega spec.  Thing is, without the ability to get to subfields, Vega Lite becomes totally useless for any object-based lists, like the one I have given as an example. BTW, all of ElasticSearch queries are returned in that format, which makes VL useless there.

I propose a slightly different approach - simply require that dots in field names must be escaped with a double backslash, just like in Vega.  E.g.   "val.val2" would mean to use a suboject, and "val\\.val2" would be literal field name. This way you address both usecases, and make Vega Lite trully useful, at least to many of my use cases.  Thanks!

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 300,
  "height": 300,
  "data": {
    "url": "https://gist.githubusercontent.com/nyurik/1d43ee9cd1c89b297e25cf8a965f4e4c/raw/31e341c72eab8f0d5dba4444c5365244b0c09221/reco2.json",
    "format": {"property": "hits.hits"}
  },
  "mark": "point",
  "encoding": {
    "x": {
      "field": "source.reco",
      "type": "quantitative"
    },
    "y": {
      "field": "source.yes",
      "type": "quantitative"
    }
  }
}
```

**Comment by nyurik** [comment]
And another reason --  making dots mean different things in different places is a bad usability.  In the above, ` "format": {"property": "hits.hits"}`  dot means field separator, but ` "field": "source.reco",` means literal.

**Comment by domoritz** [comment]
Oh wow, I didn't realize Vega treats `.` as property lookups in fields. I thought @willium fixed this together with `-` in https://github.com/vega/vega-lite/issues/2625. This should be fixed. 

I agree that users should have to escape . in field names.

**Comment by domoritz** [comment]
Fixed in #https://github.com/vega/vega-lite/pull/3141

**Comment by nyurik** [comment]
Something is still broken. With the above example data, adding "tooltip" for a line mark works ok if the data has no subfields, and doesn't work with subfields.

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 300,
  "height": 300,
  "data": {
    "url": "https://gist.githubusercontent.com/nyurik/438d0c99c408f34c192dd4ca3868c177/raw/1d69e6c9690283e1aed28a37bfda19ea7978f7c5/reco1.json",
    "format": {"property": "hits.hits"}
  },
  "mark": "line",
  "encoding": {
    "tooltip":{
      "field": "_source.dimension",
      "type": "ordinal"
    },
    "x": {
      "field": "_source.reco",
      "type": "quantitative"
    },
    "y": {
      "field": "_source.yes",
      "type": "quantitative"
    }
  }
}
```

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 300,
  "height": 300,
  "data": {
    "url": "https://gist.githubusercontent.com/nyurik/1d43ee9cd1c89b297e25cf8a965f4e4c/raw/31e341c72eab8f0d5dba4444c5365244b0c09221/reco2.json",
    "format": {"property": "hits.hits"}
  },
  "mark": "line",
  "encoding": {
    "tooltip":{
      "field": "source\\.dimension",
      "type": "ordinal"
    },
    "x": {
      "field": "source\\.reco",
      "type": "quantitative"
    },
    "y": {
      "field": "source\\.yes",
      "type": "quantitative"
    }
  }
}
```

**Comment by domoritz** [comment]
Looks like a bug in the facet aggregate that doesn't handle the subfield property. The generated code looks good.
