### ISSUE TITLE
Make default `"filled":false` for lines in GeoShapes

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#3430]
GeoShape marks currently use the default stroke and fill styles for all geometry types. While this makes sense for polygons and points (which are symbolised with fillable circles), it causes problems for lines. Lines become closed as if they were polygons and their interior filled with the current fill setting.  For `FeatureCollection` objects that contain lines overlapping with polygons, this creates unwanted `xor` overlay problems as the order of line coordinates becomes subject to the winding rule as if it were a polygon.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 200,
  "height": 200,
  "data": {
    "values": [
      {
        "type": "FeatureCollection",
        "features": [
          {
            "type": "Feature",
            "geometry": {
              "type": "Polygon",
              "coordinates": [  [  [ -2, 58 ],  [3, 58], [3, 53], [-2, 53], [-2, 58]  ]  ]
            }
          },
          {
            "type": "Feature",
            "geometry": {
              "type": "LineString",
              "coordinates": [  [ 4, 52], [4, 59], [-3, 59] ]
            }
          }
        ]
      }
    ]
  },
  "mark": "geoshape"
}
```

While filling and closing of lines can be overridden with `filled: false`, this seems like an unnecessary step for a mark that conceptually has no interior. And more significantly, for a geoshape that contains both polygons and lines, it is not currently possible to show filled polygons and unfilled lines.

Would it be possible to make the default `filled` value `false` for line features?

**Comment by kanitw** [comment]
> Would it be possible to make the default filled value false for line features?

It is possible, but that will introduce another problem when the input JSON is for creating choropleth like in https://vega.github.io/vega-lite/examples/geo_repeat.html. 

Basically you need to set `filled: true` for choropleth instead. So I don't know if changing default really make things better here.  Since I don't think there is clear answer for the better default here, I'd rather avoid breaking changes.

We do plan to add separate `fill` and `stroke` channels (https://github.com/vega/vega-lite/issues/1855), which allow to have more control over color without dealing with `filled`.  

> And more significantly, for a geoshape that contains both polygons and lines, it is not currently possible to show filled polygons and unfilled lines.

Yes, this will be a problem.  I wonder how often this happens in practice though.  

In any case, maybe `condition` support for the `fill` / `stroke` channel might solve a bit of this problem too.  But I haven't though much about what should the `test` predicate for checking if the given path is a filled polygon or filled line or not.  If you have any suggestion, feel free to propose.

**Comment by jwoLondon** [comment]
I agree that making the default filled:false for all JSON GeoShape geometry objects would not be the solution. It's more a question of whether it is possible to differentiate between GeoShape `geometry.type`s (`Polygon` and `LineString`) and render them with different styles.

Perhaps the `condition` could be used with the new `fill` and `stroke` channels something like

```javascript
 "fill": {
      "condition": {
        "test": "datum.features.geometry.type == 'LineString'",
        "value": {"filled":false}
      },
       "value": {"filled":true}
    }
```
The difficulty may be that even within the geoJSON spec, `geometry.type` can appear at a number of levels, such as within a top level `geometry` type or nested within a `FeatureCollection` or within a `GeometryCollection`. But even if it was the user's responsibility to match the `condition test` to the particular structure of their geoJSON, I think this flexibility would be an improvement.

The other possibility would be to be able to use layers and a transform filter, selecting only particular geometry types in each layer. But that feels a bit hacky, and would have the overhead of loading and filtering the same dataset several times.

**Comment by domoritz** [comment]
> But that feels a bit hacky, and would have the overhead of loading and filtering the same dataset several times.

Vega-Lite internally optimizes this away and only loads the dataset once.

**Comment by kanitw** [comment]
The filtering part will still apply a full pass twice though, so I think `condition` is a better way.  
(In any case, if there is a good predicate for filtering, that means we have a good predicate for conditioning.)

**Comment by kanitw** [comment]
@jwoLondon   Now we have fill and stroke -- can you help test if it resolves this problem?

**Comment by jwoLondon** [comment]
I've yet to find a way of getting this to work. Even with the new fill and stroke channels (which are great btw), we still need a way of referencing the geometry type in order to encode it. This in turn runs into the problems of referencing nested items (#3432 and #3369).

**Comment by kanitw** [comment]
@jwoLondon  Given both #3432 and #3369 are now fixed, is this issue resolved yet?

**Comment by jwoLondon** [comment]
It is probably my ignorance of how objects are referenced in Vega-Lite, but I still cannot find a way of referencing the geometry type, so don't know how to resolve the issue yet. Here is a start of (non-working) example. Any ideas how we could specify an encoding that says if the geometry type is a `LineString` encode it with no fill, otherwise fill it (`features.geometry.type` is clearly wrong)?

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 200,
  "height": 200,
  "data": {
    "values": {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "geometry": {"type": "Point","coordinates": [5, 55]}
        },
        {
          "type": "Feature",
          "geometry": {"type": "Polygon","coordinates": [[[-2,58],[3,58],[3,53],[-2,53],[-2,58]]]}
        },
        {
          "type": "Feature",
          "geometry": {"type": "LineString","coordinates": [[4,52],[4,59],[-3,59]]}
        }
      ]
    }
  },
  "projection": {"type": "orthographic"},
  "encoding": {
    "opacity": {
      "condition": {
        "test": "features.geometry.type == 'Polygon' ",
        "value": 1
      },
      "value": 0
    }
  },
 "mark": "geoshape"
}
```

**Comment by iliatimofeev** [comment]
![visualization 48](https://user-images.githubusercontent.com/11561581/45000864-01525a00-afd1-11e8-85f7-fff7bee1a7c4.png)

It is a tree as it is described and so it is not clear which node you are testing, so transform it to the the array of features and then access through `datum.geometry.type` 
I found a way to solve your question with `"fill"{...."value": "rgba(0,0,0,0)"}`, but it is hack, I believe. And I couldn't setup a proper legend in that case. But I could help as workaround.  [see vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgB3RgBMW2MNIAMR9REgpG1fAeOmNkHejyYcoCOYBm3AE4Y82MCQeACehMjYkArKapCEPtzhPqGRnsjOrD7IsJAAvmYekBToYqzZBu4e5qHhBpAAYul4mcgAwtxiYsjweDwqBVWQaRlZOTgA2hpVEJXThTUROA1NLWpTc1DUyNyoyHg+IRXBYYtQAArcjEoBqpDw3L46V87lEwCsqmBvbwC6uetVfIAjyzDbHWpLRojCIDMFbHZ7A5HBZ1C5iELUGK3e6PZ54V5gcZEkTSVRvAAcP1U4wAzGTKdS6W8aVTxiSySzqeyKT9ef8NmAgQLQXNwadltC1gLzPDdvtDm4xXUADJXZAAZX2V2osRxPieSheY0J4wALGTpKzzW8AJyskRMu1-YEQfnTH7rN1CqDxbhybq9GKKlFLXwsbjUHzoQiIRjwPIFSDIJT3A06tzrIaMToVYF3ZRPQMqDMC4LZAJLJzNVAMbZyg50BZgAC8zbAAHI0RjlO2oLDBp5GMgxDo6rLESFGycpWCQ5AlDtnmJIMDvYNiqVxT5qOx0AAKUyH1RGACUK8BsMgsH23AA1osgoPh6OsJBx-Kp7VbnOF6gl3kQA0IVIAwHxb0CJVX3hWBEGjGErxve8AHVdH0LA6SzToAHlCHQeBmAVIw6Def5ciAA)

By the way you are using clockwise coordinates in polygons as d3 wants but it is opposed to [rfc7946](https://tools.ietf.org/html/rfc7946#section-3.1.6) . What is your real data source provides?
