### ISSUE TITLE
VL 4.0.0-beta.1 breaks Vega-embed

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega-lite#5354]
Any attempt to embed a VL spec using VL4.0.0-beta.1 fails to compile. For example, the [tutorial example](https://vega.github.io/vega-lite/tutorials/getting_started.html#embed) results in the following console error and fails to render

```
embed.js:33 Uncaught (in promise) TypeError: Cannot read property 'compile' of undefined
    at Object.vega-lite (embed.js:33)
    at embed.js:134
    at Generator.next (<anonymous>)
    at tslib.es6.js:73
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:69)
    at embed (embed.js:96)
    at wrapper (index.js:17)
    at tutorialExample.html:55
vega-lite @ embed.js:33
(anonymous) @ embed.js:134
(anonymous) @ tslib.es6.js:73
__awaiter @ tslib.es6.js:69
embed @ embed.js:96
wrapper @ index.js:17
(anonymous) @ tutorialExample.html:55
```

Linking instead to the `beta.0` library works as expected.

**Comment by domoritz** [comment]
Also visible on the demo page: https://vega.github.io/vega-lite/site/demo.html

**Comment by domoritz** [comment]
Ahh, it's because Vega-Lite now exports `vegaLite` instead of `vl`.

**Comment by domoritz** [comment]
See https://github.com/vega/vega-lite/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed

**Comment by domoritz** [comment]
Fixed in Vega-Embed 5

**Comment by jwoLondon** [comment]
I still see the same problem with Vega-embed 5 and VL4.0.0-beta.1

**Comment by domoritz** [comment]
🤦‍♂  I forgot to push a change (I'll blame jetlag and a cold for this). Fixed in the latest release. I also added backward compatibility with pre Vega-Lite 4 versions.
