### ISSUE TITLE
Improve css for vertical slider alignment

### ISSUE THREAD

**Issue by joelostblom** [vega/vega-lite#8740]
Currently, sliders show up a bit above the text, which looks a bit wonky:

![image](https://user-images.githubusercontent.com/4560057/221440642-80b81e4d-b59b-48fe-aea7-c0044cc72236.png)

This can be fixed via CSS and I have a solution locally that shows the slider more centered vertically and in line with the text. However, I can't find the CSS file where I could suggest this change (I tried looking through a few of the repos in the org already but it escaped me), where is it located?

**Comment by domoritz** [comment]
We merged https://github.com/vega/vega-lite/pull/8580. Where is this chart? I can help find the css for it.

**Comment by joelostblom** [comment]
Haha, that's funny, I forgot about my own PR from just a few months ago. Too much going on xD

I still see the issue in e.g. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJgpgzgxgTgSwA4BcEHsB2IBcICCABLAIYooRxIA26KxAFugO4KYDmhTcUESLlQiUxhCAWwTVohJIPYlqtTFEIAzdHEIA3EonQBXFTF1QAdCAA0IJLpJiouANqhMdiLhBQGJWZZA7qfXc8GAQ4GCk-ACM2MFxQNiR9FA9eKRgUq3RUDGUnEF04Fj9Q8MirKABHfV13K3h0KAcrMAQ7LDirFERhdnKQbraOKQBafSQ-Qd7RsBZsLp7hiBHEdgZMgcW+5alVDeYIMHY6z270AGsTgFkRgEYLO4AJW4A1W8e7gC0-K4AGC1MAFYADKmABsAIAHKDAQDbsD7iNTABmUHIh6mAAswP+d2BSPRSOxdwxqKRsNM8KRENM0P+QO+AF0AL7MiwuNweaYnAJBXD-EAxETxECJZIeOC9E4SbA4EbIsECsQkAAeuAVAqgFAmOFurPZIFcYmCngQAC8eQo+ThkQKhXEcAlMEkUnhJRxpWx+VZlWrdb8A5rtbhbgH9RzjakzpcAOoIMAoBh+XnBABMVntIrFrpA7uOfhl3pAvpDQb4-KBrMZLTIJBF+jg1A8YFrAHpjDxTAArKBYEBs4u6c4ilAAT18eH4bA23JFEBVSDgXKW-Yq5uCoHni9S69Xnm8E83C6XeC8PncA61RVj8cTc+PUevEDjCaT+pAEEwMHQrQ4Ir9oCqAgEDUA6ICPBovD8AcS5dOOJrVMIaAoGQCBaBeVijiKQEgWBVySNAAD6shwIRADiChKJM8EeIhmDIah6H9qyQA) and I see that I added the `.example` selector in the CSS change in #8580, does that mean it will only change the examples in the documentation? Is there anyway to change the default CSS that all Vega charts use so that sliders by default are aligned with the numbers? Or maybe it is just because there hasn't been a release since that PR was merged?
